version: '3.3'

networks:
  mrjb_offnet:

services:   
  mssql:
    build: ./docker/mssql
    container_name: mrjb_offnet_mssql
    ports:
      - 1433:1433
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'NyLct4D@7K{s'
    volumes:
     - ./docker/data/mssql/:/var/opt/mssql/data
    networks:
      - mrjb_offnet